- name: Create Share Directory
  ansible.builtin.file:
    path: "{{ storage_dir }}"
    state: directory
    owner: root
    group: root
    mode: 'u=rw,g=rw,o=r'
    recurse: true

- name: Install Transmission
  ansible.builtin.package:
    name: 
      - transmission-cli
    state: present

- name: Install NFS
  ansible.builtin.package:
    name:
      - nfs-kernel-server
    state: present

- name: Config NFS
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ storage_dir }} {{ item }}(ro,sync,subtree_check,all_squash,insecure,anonuid=0,anongid=0)"
  loop: "{{ nfs_whitelist }}"

- name: Export NFS Shares
  ansible.builtin.shell:
    cmd: exportfs -a

- name: Restart NFS
  ansible.builtin.systemd_service:
    name: nfs-server
    state: restarted
      
- name: Install Samba
  ansible.builtin.package:
    name: 
      - samba
    state: present

- name: Configure Samba
  ansible.builtin.blockinfile:
    dest: /etc/samba/smb.conf
    content: |
      [macbookair]
        comment = share the share directory
        path = {{ storage_dir }}
        read only = yes
        browsable = yes
        guest ok = yes
        force user = ryanmissett

- name: Restart Samba
  ansible.builtin.systemd_service:
    name: samba
    state: restarted
